# Generated by Django 6.0.4 on 2026-05-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('donor_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('memorial', 'Memorial')], max_length=20)),
                ('type_date', models.DateField()),
                ('food', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_birthday', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_birthday', models.DateField(blank=True, null=True)),
                ('child_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_birthday', models.DateField(blank=True, null=True)),
                ('wife_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wife_birthday', models.DateField(blank=True, null=True)),
                ('wife_anniversary', models.DateField(blank=True, null=True)),
                ('parents_anniversary', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
