# Generated by Django 6.0.4 on 2026-05-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('memorial', 'Memorial')], max_length=20)),
                ('occasion_date', models.DateField()),
                ('food', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='donors.donor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('confirmed', 'Confirmed'), ('next_time', 'Next Time')], max_length=20)),
                ('year', models.IntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='donors.donor')),
            ],
            options={
                'unique_together': {('donor', 'event_type', 'year')},
            },
        ),
    ]
